name_prefix = "acc"
key_name = "acc-key"
ami_id = "ami-0c9c942bd7bf113a2"
ecr_repository_name = "acc-app"
app_instance_type = "t3.small"
bastion_instance_type = "t3.micro"
monitoring_instance_type = "t3.medium"